# Database instance
services:
  mssql:
    image: microsoft/mssql-server-windows-developer #mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw@rd